export const fieldsLead = [
  {
    name: "createdAt",
    label: "Data de cadastro",
    type: "datetime",
    value: "",
  },
  {
    name: "name",
    label: "Nome da empresa",
    type: "string",
    value: "",
    default: true,
  },
  {
    name: "legalName",
    label: "Razão Social",
    type: "string",
    value: "",
    size: 4,
  },
  {
    name: "cnpj",
    label: "CNPJ",
    type: "string",
    value: "",
    size: 4,
  },
  {
    name: "ie",
    label: "I.E.",
    type: "string",
    value: "",
    size: 4,
  },
  {
    name: "email",
    label: "Email da Empresa",
    type: "string",
    value: "",
    size: 4,
  },
  {
    name: "phone",
    label: "Telefone da Empresa",
    type: "string",
    value: "",
    size: 4,
  },
  {
    name: "sintegraContribuinteIcms",
    label: "Contribuinte ICMS",
    type: "boolean",
    value: "",
    size: 3,
  },
  {
    name: "zipCode",
    label: "CEP",
    type: "string",
    value: "",
    size: 3,
  },
  {
    name: "streetAddress",
    label: "Rua",
    type: "string",
    value: "",
    size: 4,
  },
  {
    name: "streetAddressNumber",
    label: "Número",
    type: "string",
    value: "",
    size: 2,
  },
  {
    name: "streetAddressLine2",
    label: "Complemento",
    type: "string",
    value: "",
    size: 3,
  },
  {
    name: "neighborhood",
    label: "Bairro",
    type: "string",
    value: "",
    size: 4,
  },
  {
    name: "city",
    label: "Cidade",
    type: "object",
    size: 4,
    object: {
      name: "city",
      singular: "city",
      plural: "cities",
      label: "Cidade",
    },
    value: "",
    fields: [
      {
        name: "fullName",
        label: "Cidade",
        type: "string",
        value: "",
        default: true,
      },
    ],
  },
  {
    name: "website",
    label: "Website",
    type: "string",
    value: "",
    size: 6,
  },
  {
    name: "facebook",
    label: "Facebook",
    type: "string",
    value: "",
    size: 6,
  },
  {
    name: "instagram",
    label: "Instagram",
    type: "string",
    value: "",
    size: 6,
  },
  {
    name: "linkedin",
    label: "LinkedIn",
    type: "string",
    value: "",
    size: 6,
  },
  {
    name: "message",
    label: "Mensagem",
    type: "string",
    value: "",
    size: 12,
  },

  {
    name: "user",
    label: "Novo usuário",
    type: "object-exploded",
    size: 6,
    object: {
      name: "usersPermissionsUser",
      singular: "usersPermissionsUser",
      plural: "usersPermissionsUsers",
      label: "Novo usuário",
    },
    value: "",
    fields: [
      {
        name: "name",
        label: "Novo usuário",
        type: "string",
        value: "",
      }, //,
      {
        name: "email",
        label: "Email",
        type: "string",
        value: "",
      }, //,
      {
        name: "phone",
        label: "Celular",
        type: "string",
        value: "",
      }, //,
      {
        name: "confirmed",
        label: "Confirmado por email",
        type: "boolean",
        value: "",
      }, //,
      {
        name: "blocked",
        label: "Bloqueado",
        type: "boolean",
        value: "",
      }, //,
      {
        name: "role",
        label: "Tipo de acesso",
        type: "object",
        size: 6,
        filter: { id: { eq: 2 } },
        hide: true,
        object: {
          name: "role",
          singular: "role",
          plural: "roles",
          label: "Tipo de acesso",
        },
        fields: [
          {
            name: "name",
            label: "Nome",
            type: "string",
            value: "",
            default: true,
          },
          {
            name: "type",
            label: "Tipo",
            type: "string",
            value: "",
          }, //
        ],
      }, //,
    ],
  },

  {
    name: "owner",
    label: "Responsável",
    type: "object",
    size: 6,
    object: {
      name: "usersPermissionsUser",
      singular: "usersPermissionsUser",
      plural: "usersPermissionsUsers",
      label: "Responsável",
    },
    value: "",
    fields: [
      {
        name: "name",
        label: "Responsável",
        type: "string",
        value: "",
      }, //,
    ],
  },
];
