export const fieldsPrice = [
  {
    name: "id",
    label: "Id",
    type: "string",
    value: "",
    size: 2,
    hide: true,
  },

  {
    name: "enabled",
    label: "Ativo",
    type: "boolean",
    value: "",
    //filter: {},
    size: 1,
    // hide: true,
  },
  {
    name: "sku",
    label: "SKU",
    type: "string",
    value: "",
    size: 2,
    //  hide: true,
  },
  {
    name: "accessLevel",
    label: "Nível de acesso",
    type: "accessLevel",
    value: "",
  },

  {
    name: "product",
    label: "Produto",
    type: "object-exploded",
    size: 12,
    object: {
      name: "product",
      singular: "product",
      plural: "products",
      label: "Produto",
    },
    value: "",
    fields: [
      {
        name: "id",
        label: "Id",
        type: "number",
        // value: "none",
        filter: {},
        hide: true,
      },
      {
        name: "name",
        label: "Nome do produto",
        type: "string",
        value: "",
        size: 12,
      },

      {
        name: "type",
        label: "Tipo",
        type: "deviceType",
        value: "none",
        filter: {},
      },
      {
        name: "erpId",
        label: "SKU Produto",
        type: "string",
        value: "",
      },
    ],
  },
  {
    name: "valueInCents",
    label: "Preço",
    type: "price",
    value: "",
  },
  {
    name: "costInCents",
    label: "Custo",
    type: "price",
    value: "",
    hide: true,
  },
  {
    name: "priceList",
    label: "Lista de preço",
    type: "object",
    size: 4,
    object: {
      name: "priceList",
      singular: "priceList",
      plural: "priceLists",
      label: "Lista de preço",
    },
    value: "",
    fields: [
      {
        name: "id",
        label: "id",
        type: "number",
        value: "",
        hide: true,
      },
      {
        name: "name",
        label: "Nome",
        type: "string",
        value: "",
      },

      {
        name: "shippingDate",
        label: "Data de entrega",
        type: "shippingDate",
        value: "",
      },
    ],
  },
  {
    name: "availableQuantity",
    label: "Quantidade disponível",
    type: "integer",
    value: "",
    editable: false,
  },
  {
    name: "reservedQuantity",
    label: "Quantidade reservada",
    type: "integer",
    value: "",
    editable: false,
  },
  {
    name: "initialQuantity",
    label: "Quantidade total",
    type: "integer",
    value: "",
  },
  // {
  //   name: "reservedQuantityPreSales",
  //   label: "Quantidade reservada pré-venda",
  //   type: "integer",
  //   value: "",
  //   editable: false,
  // },

  {
    name: "minimunQuantityLevel",
    label: "Quantidade mínima estoque",
    type: "integer",
    value: "",
  },
  {
    name: "isQuantityControlled",
    label: "Ativar controle de estoque",
    type: "boolean",
    value: "",
  },
  {
    name: "available",
    label: "Permitir venda/Ítem pré venda chegou",
    type: "boolean",
    value: "",
    // hide: true,
  },
];
