import { Quote, SapOrder } from "@/types/quote";
import { formatDateToSap } from "../format/format-date-to-sap";

export function formatSapPurchaseRequest(sapOrder: SapOrder, quote: Quote) {
  let d = new Date();
  let d2 = new Date(d.toISOString().substring(0, 10));

  let sapPurchaseRequest: any = {
    method: "POST",
    requestId: sapOrder.id,
    url: "/b1s/v1/PurchaseRequests",
    DocType: "dDocument_Items",
    HandWritten: "tNO",
    Printed: "psNo",
    DocDate: formatDateToSap(new Date()),
    DocDueDate: "2025-04-21T00:00:00Z",
    DocCurrency: "R$",
    DocRate: 1,
    // Reference1: "2055",
    DocTime: "14:14:00",
    SalesPersonCode: -1,
    TransportationCode: -1,
    Confirmed: "tYES",
    SummeryType: "dNoSummary",
    ContactPersonCode: 0,
    ShowSCN: "tNO",
    Series: 56,
    TaxDate: formatDateToSap(new Date()),
    PartialSupply: "tYES",
    DocObjectCode: "oPurchaseRequest",
    DiscountPercent: 0,
    CreationDate: formatDateToSap(new Date()),
    UpdateDate: formatDateToSap(new Date()),
    FinancialPeriod: 90,
    UserSign: 1,
    VatSum: 0,
    VatSumSys: 0,
    VatSumFc: 0,
    NetProcedure: "tNO",
    DocTotalFc: 0,
    DocTotalSys: quote?.integratorServicesInCents / 100,
    RevisionPo: "tNO",
    RequriedDate: formatDateToSap(new Date()),
    BlockDunning: "tNO",
    Submitted: "tNO",
    Segment: 0,
    PickStatus: "tNO",
    Pick: "tNO",
    PaymentBlock: "tNO",
    MaximumCashDiscount: "tNO",
    Reserve: "tNO",
    WareHouseUpdateType: "dwh_No",
    Rounding: "tNO",
    WTApplied: 0,
    WTAppliedFC: 0,
    BillOfExchangeReserved: "tNO",
    WTAppliedSC: 0,
    TotalEqualizationTax: 0,
    TotalEqualizationTaxFC: 0,
    TotalEqualizationTaxSC: 0,
    NumberOfInstallments: 1,
    ApplyTaxOnFirstInstallment: "tNO",
    TaxOnInstallments: "toiProportionally",
    DocumentSubType: "bod_None",
    Address2:
      "RuaAGRIM SUGAYA,288\rLOTE 35 A SALA 04 A\r08.260-030-SÃO PAULO-SP\rBRASIL",
    DocumentStatus: "bost_Open",
    PeriodIndicator: "Padrão",
    UseShpdGoodsAct: "tNO",
    //BPL_IDAssignedToInvoice: 8,
    BPL_IDAssignedToInvoice: 8,
    ReserveInvoice: "tNO",
    SequenceModel: "0",
    UseCorrectionVATGroup: "tNO",
    TotalDiscount: 0,
    DownPaymentAmount: 0,
    DownPaymentPercentage: 0,
    DownPaymentType: "dptInvoice",
    DownPaymentAmountSC: 0,
    DownPaymentAmountFC: 0,
    VatPercent: 0,
    ControlAccount: "",
    InsuranceOperation347: "tNO",
    ArchiveNonremovableSalesQuotation: "tNO",
    StartFrom: "pdt_None",
    NTSApproved: "tNO",
    BPLName: "07 - COR SOLAR",
    VATRegNum: "14.197.209/0010-92",
    IsAlteration: "tNO",
    CancelStatus: "csNo",
    Requester: "INTEGRACAO.E-COMMERCE",
    RequesterName: "INTEGRACAO E-COMMERCE",
    RequesterBranch: -2,
    RequesterDepartment: -2,
    SendNotification: "tNO",
    ReqType: 12,
    ReqCode: "INTEGRACAO.E-COMMERCE",
    DocumentDelivery: "ddtNoneSeleted",
    ReuseDocumentNum: "tNO",
    ReuseNotaFiscalNum: "tNO",
    PrintSEPADirect: "tNO",
    InterimType: "boidt_None",
    RelatedType: -1,
    ExcludeFromTaxReportControlStatementVAT: "tNO",
    UpdateTime: "14:14:21",
    CommissionTrade: "ct_Empty",
    CommissionTradeReturn: "tNO",
    FatherType: "cPayments_sum",
    ShipState: "",
    DataVersion: 1,
    InventoryStatus: "bost_Open",
    PlasticPackagingTaxRelevant: "tNO",
    NotRelevantForMonthlyInvoice: "tNO",
    U_B1SYS_ImportProc: 1,
    U_operacao: "1",
    U_indFinal: "0",
    U_indPres: "9",
    U_finNfe: "0",
    U_finNf3: "0",
    U_UPDocImp: "N",
    U_UPDfObsL: "N",
    U_UPEtpPro: "0",
    U_UPPrcDep: "N",
    U_UPP_ProcessoConferenciaEntreFiliais: "N",
    U_UPP_ProcessoFaturamentoDepositoFechado: "N",
    U_UPR_DocLibOpRetrabalho: "N",
    U_UPR_DocRetOpRetrab: "N",
    U_UPR_QuestTrocaLote: "N",
    U_UPR_EstornoPrd: "N",
    U_UPRemAvu: "N",
    U_UPNFRtSC: "0",
    U_UPBenCmp: "N",
    U_UPDcRfNI: "N",
    U_UPNotaServico: "N",
    U_UPAsRtOP: "N",
    U_UPBlocoK: "N",
    U_UPIgnFch: "N",
    U_UPW_StatusRecebimento: "1",
    U_UPW_StatusExpedicao: "1",
    U_UPW_LiberadoExpedicao: "N",
    U_UPW_WMSConfEmbarq: "N",
    U_UPW_StatusInventario: "1",
    U_CC_Inspecao: "C",
    U_CS_ValorIntegracao: 0,
    U_BoeServiceStatus: "0",
    U_DanfeServiceStatus: "0",
    U_XmlServiceStatus: "0",
    U_BoeSavedByService: "0",
    U_NrTentaGerarBoleto: 0,
    U_DanfePrintedByServ: "0",
    U_GenerateBoeByServ: "1",
    U_NrImpressaoNfe: 0,
    U_BoletoGeradoServ: "0",
    U_UPR_BeneficiamentoVendas: "N",
    U_UPP_HabilitaFreteManual: "N",
    U_UPP_ValorFrete: 0,
    U_UPP_TipoCorte: "N",
    U_UPP_ErroSaidaCorte: "N",
    U_UPR_StatusIntegracaoPPI: "0",
    U_UPP_StatusFat: "0",
    U_UPR_MargemContPerc: 0,
    U_UPR_TotalComissRS: 0,
    U_UPR_ComissPerc: 0,
    U_UPR_EmbTotalRS: 0,
    U_UPR_OnusFinanRS: 0,
    U_UPR_OnusFinPerc: 0,
    U_UPR_MargemContRS: 0,
    U_UPR_DescAplTotal: 0,
    U_UPR_MediaDescPerc: 0,
    U_UPR_DescTotalRS: 0,
    U_UPR_CustoTotal: 0,
    U_UPR_PremioTotal: 0,
    U_UPR_MargemComRS: 0,
    U_Autorizar: "N",
    U_U_CC_Suframa: "N",
    U_TX_DescLinhaDeveDeduzirBc: "1",
    U_CC_AtualizaInfo: "N",
    Document_ApprovalRequests: [],
    DocumentLines: [
      {
        LineNum: 0,
        ItemCode: "SV000025",
        ItemDescription: "PRESTAÇÃO DE SERVIÇO - TERCEIROS",
        Quantity: 1,
        ShipDate: null,
        Price: quote?.integratorServicesInCents / 100,
        PriceAfterVAT: quote?.integratorServicesInCents / 100,
        Currency: "R$",
        Rate: 0,
        DiscountPercent: 0,
        VendorNum: "",
        SerialNum: null,
        WarehouseCode: "20.07",
        SalesPersonCode: -1,
        CommisionPercent: 0,
        TreeType: "iNotATree",
        AccountCode: "",
        UseBaseUnits: "tNO",
        SupplierCatNum: "",
        CostingCode: "Solar",
        ProjectCode: "",
        Factor1: 1,
        Factor2: 1,
        Factor3: 1,
        Factor4: 1,
        BaseType: -1,
        Volume: 0,
        VolumeUnit: 4,
        Width1: 0,
        Width2: 0,
        Address: "",
        TaxCode: "",
        TaxType: "tt_Yes",
        TaxLiable: "tYES",
        PickStatus: "tNO",
        PickQuantity: 0,
        FreeText: "",
        ShippingMethod: 1,
        POTargetEntry: "",
        CorrectionInvoiceItem: "ciis_ShouldBe",
        CorrInvAmountToStock: 0,
        CorrInvAmountToDiffAcct: 0,
        AppliedTax: 0,
        AppliedTaxFC: 0,
        AppliedTaxSC: 0,
        WTLiable: "tNO",
        DeferredTax: "tNO",
        EqualizationTaxPercent: 0,
        TotalEqualizationTax: 0,
        TotalEqualizationTaxFC: 0,
        TotalEqualizationTaxSC: 0,
        NetTaxAmount: 0,
        NetTaxAmountFC: 0,
        NetTaxAmountSC: 0,
        MeasureUnit: "UNID",
        UnitsOfMeasurment: 1,
        LineTotal: quote?.integratorServicesInCents / 100,
        TaxPercentagePerRow: 0,
        TaxTotal: 0,
        ConsumerSalesForecast: "tNO",
        ExciseAmount: 0,
        TaxPerUnit: 0,
        TotalInclTax: 0,
        DistributeExpense: "tNO",
        RowTotalFC: 0,
        //"RowTotalSC": quote?.integratorServicesInCents/100,
        LastBuyInmPrice: 0,
        LastBuyDistributeSumFc: 0,
        LastBuyDistributeSumSc: 0,
        LastBuyDistributeSum: 0,
        StockDistributesumForeign: 0,
        StockDistributesumSystem: 0,
        StockDistributesum: 0,
        StockInmPrice: 0,
        PickStatusEx: "dlps_NotPicked",
        TaxBeforeDPM: 0,
        TaxBeforeDPMFC: 0,
        TaxBeforeDPMSC: 0,
        CFOPCode: "",
        Usage: 16,
        TaxOnly: "tNO",
        VisualOrder: 0,
        BaseOpenQuantity: 0,
        UnitPrice: quote?.integratorServicesInCents / 100,
        LineStatus: "bost_Open",
        PackageQuantity: 1,
        Text: "",
        LineType: "dlt_Regular",
        ChangeAssemlyBoMWarehouse: "N",
        GrossBuyPrice: 0,
        GrossProfitTotalBasePrice: 0,
        CostingCode2: "4201",
        RemainingOpenQuantity: 1,
        OpenAmount: quote?.integratorServicesInCents / 100,
        OpenAmountFC: 0,
        OpenAmountSC: quote?.integratorServicesInCents / 100,
        RequiredDate: formatDateToSap(new Date()),
        RequiredQuantity: 0,
        WithoutInventoryMovement: "tNO",
        Surpluses: 0,
        DefectAndBreakup: 0,
        Shortages: 0,
        ConsiderQuantity: "tNO",
        PartialRetirement: "tNO",
        RetirementQuantity: 0,
        RetirementAPC: 0,
        ThirdParty: "tNO",
        GrossProfit: 0,
        GrossProfitFC: 0,
        GrossProfitSC: 0,
        PriceSource: "dpsActivePriceList",
        LineVendor: quote?.enterprise?.sapSupplierCode,
        UoMEntry: 56,
        UoMCode: "UNIDADE",
        InventoryQuantity: 1,
        RemainingOpenInventoryQuantity: 1,
        Incoterms: 0,
        TransportMode: 0,
        ItemType: "dit_Item",
        ChangeInventoryQuantityIndependently: "tNO",
        FreeOfChargeBP: "tNO",
        GrossPrice: quote?.integratorServicesInCents / 100,
        GrossTotal: quote?.integratorServicesInCents / 100,
        GrossTotalFC: 0,
        GrossTotalSC: quote?.integratorServicesInCents / 100,
        NCMCode: -1,
        IndEscala: "tNO",
        CtrSealQty: 0,
        ReverseCharge: "tNO",
        WeightOfRecycledPlastic: 0,
        CUSplit: "tNO",
        ListNum: -1,
        U_B1SYS_IVAST: 0,
        U_B1SYS_QtyPerTaxUoM: 0,
        U_B1SYS_RevenueInd: "0",
        U_UPClaRef: "-1",
        U_UPRefugo: "N",
        U_UPR_SubProduto: "N",

        U_UPR_CalcularPor: "D",

        U_UPP_StatusFat: "0",
        U_IcmsCte: "Nenhum",
        LineTaxJurisdictions: [],
        DocumentLineAdditionalExpenses: [],
      },
    ],
    ElectronicProtocols: [],
    DocumentSpecialLines: [],
    TaxExtension: {
      TaxId0: null,
      TaxId1: null,
      TaxId2: null,
      TaxId3: null,
      TaxId4: null,
      TaxId5: null,
      TaxId6: null,
      TaxId7: null,
      TaxId8: null,
      TaxId9: null,
      State: "",
      County: "",
      NetWeight: 0,
      GrossWeight: 0,
      StreetS: "AGRIM SUGAYA",
      BlockS: "COLONIA (ZONA LESTE)",
      BuildingS: "LOTE 35 A SALA 04 A",
      CityS: "SÃO PAULO",
      ZipCodeS: "08.260-030",
      CountyS: "5344",
      StateS: "SP",
      CountryS: "BR",
      MainUsage: 16,
      ImportOrExportType: "et_IpmortsOrExports",
      BoEValue: 0,
    },
    AddressExtension: {
      ShipToStreet: "AGRIM SUGAYA",
      ShipToStreetNo: "288",
      ShipToBlock: "COLONIA (ZONA LESTE)",
      ShipToBuilding: "LOTE 35 A SALA 04 A",
      ShipToCity: "SÃO PAULO",
      ShipToZipCode: "08.260-030",
      ShipToCounty: "5344",
      ShipToState: "SP",
      ShipToCountry: "BR",
      ShipToAddressType: "Rua",
      U_UPP_EndFatS: "N",
      U_UPP_EndFatB: "N",
    },
    DocumentReferences: [
      {
        LineNumber: 1,
        // RefDocEntr: 9912,
        // RefDocNum: 3273,

        RefDocEntr: sapOrder.DocEntry,
        RefDocNum: sapOrder.DocNum,
        RefObjType: "rot_SalesOrder",
        IssueDate: formatDateToSap(new Date()),
        IssuerCode: "31",
        Model: "0",
        RefAccKey: "",
        RefAmount: 0,
        LinkRefTyp: "lrt_00",
      },
    ],
  };
  return sapPurchaseRequest;
}
